version: 0.2
phases:
  install:
    commands:
      - echo installign nginx
      - sudo apt-get update -y
      - sudo apt-get install nginx -y
  build:
    commands:
      - echo build started on `date`
      # - sudo rm /var/www/html/index.html
      - cp index.html /var/www/html
  post_build:
    commands:
      - echo configuring nginx done
artifacts:
    files:
      - /var/www/html/index.html 