version: 0.2
phases:
  install:
    runtime-versions:
      java: correcto11
  pre_build:
    commands:
      echo nothing in prebuild phases
  build:
    commands:
      - echo build started on `date`
      - mvn install
  post_build:
    commands:
      - echo build completed on `date`
artifacts:
  files:
    - target/messageUtil-1.0.jar